services:
  - type: web
    name: medical-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: medical-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: medical-backend
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
