import { ethers } from "ethers";

// ── Contract Info ────────────────────────────────────────────────────────────
// This file is auto-generated by the deploy script; ensure you've run:
//   cd blockchain && npx hardhat run scripts/deploy.js --network localhost
let contractInfo = null;

async function loadContractInfo() {
    if (contractInfo) return contractInfo;
    try {
        const mod = await import("../contracts/MedicalAccess.json");
        contractInfo = mod.default;
        return contractInfo;
    } catch {
        throw new Error(
            "Contract not deployed yet. Run the deploy script first.\n" +
            "cd blockchain && npx hardhat run scripts/deploy.js --network localhost"
        );
    }
}

// ── Provider / Signer ────────────────────────────────────────────────────────
export async function getProvider() {
    if (!window.ethereum) {
        throw new Error("MetaMask not found. Please install the MetaMask extension.");
    }
    return new ethers.BrowserProvider(window.ethereum);
}

export async function getSigner() {
    const provider = await getProvider();
    await provider.send("eth_requestAccounts", []);
    return provider.getSigner();
}

export async function getContract(withSigner = true) {
    const info = await loadContractInfo();
    const signerOrProvider = withSigner ? await getSigner() : await getProvider();
    return new ethers.Contract(info.address, info.abi, signerOrProvider);
}

// ── Wallet ───────────────────────────────────────────────────────────────────
export async function connectWallet() {
    const signer = await getSigner();
    return signer.getAddress();
}

export async function getConnectedAddress() {
    if (!window.ethereum) return null;
    const accounts = await window.ethereum.request({ method: "eth_accounts" });
    return accounts[0] || null;
}

// ── Contract Calls ───────────────────────────────────────────────────────────
export async function registerOnChain(role) {
    const contract = await getContract();
    const tx = await contract.register(role);
    const receipt = await tx.wait();
    return receipt;
}

export async function requestAccess(patientAddress) {
    const contract = await getContract();
    const tx = await contract.requestAccess(patientAddress);
    const receipt = await tx.wait();
    return receipt;
}

export async function grantAccess(doctorAddress) {
    const contract = await getContract();
    const tx = await contract.grantAccess(doctorAddress);
    const receipt = await tx.wait();
    return receipt;
}

export async function revokeAccess(doctorAddress) {
    const contract = await getContract();
    const tx = await contract.revokeAccess(doctorAddress);
    const receipt = await tx.wait();
    return receipt;
}

export async function addRecordOnChain(fileHashHex) {
    const contract = await getContract();
    // fileHashHex should be a 0x-prefixed 32-byte hex string
    const tx = await contract.addRecord(fileHashHex);
    const receipt = await tx.wait();
    return receipt;
}

export async function checkAccess(patientAddress, doctorAddress) {
    const contract = await getContract(false); // read-only
    return contract.checkAccess(patientAddress, doctorAddress);
}

// ── Event Listener (for Access Log) ──────────────────────────────────────────
export async function listenToEvents(callback) {
    const info = await loadContractInfo();
    const provider = await getProvider();
    const contract = new ethers.Contract(info.address, info.abi, provider);

    const handlers = {
        AccessRequested: (doctor, patient, timestamp, event) =>
            callback({ type: "AccessRequested", doctor, patient, timestamp: Number(timestamp), event }),
        AccessGranted: (doctor, patient, timestamp, event) =>
            callback({ type: "AccessGranted", doctor, patient, timestamp: Number(timestamp), event }),
        AccessRevoked: (doctor, patient, timestamp, event) =>
            callback({ type: "AccessRevoked", doctor, patient, timestamp: Number(timestamp), event }),
        RecordAdded: (patient, fileHash, timestamp, event) =>
            callback({ type: "RecordAdded", patient, fileHash, timestamp: Number(timestamp), event }),
    };

    Object.entries(handlers).forEach(([name, fn]) => contract.on(name, fn));

    // Return cleanup function
    return () => {
        Object.keys(handlers).forEach((name) => contract.off(name, handlers[name]));
    };
}

// ── Utility ───────────────────────────────────────────────────────────────────
export function shortenAddress(addr) {
    if (!addr) return "";
    return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
}
